### ISSUE TITLE
Automatically target multiple frameworks during the NuGet Package

### ISSUE THREAD

**Issue by fabriciorissetto** [fabriciorissetto/KeystrokeAPI#1]
http://brian-federici.com/blog/2013/4/17/automatically-target-multiple-frameworks-in-your-nuget-package

**Comment by CarbonMan** [comment]
That is my problem. When installing through the package manager console I get:

Attempting to gather dependencies information for package 'KeystrokeAPI.1.0.6' with respect to project 'ConsoleApplication1', targeting '.NETFramework,Version=v4.5.2'
Attempting to resolve dependencies for package 'KeystrokeAPI.1.0.6' with DependencyBehavior 'Lowest'
Resolving actions to install package 'KeystrokeAPI.1.0.6'
Resolved actions to install package 'KeystrokeAPI.1.0.6'
Install failed. Rolling back...
Package 'KeystrokeAPI 1.0.6' does not exist in project 'ConsoleApplication1'
Package 'KeystrokeAPI 1.0.6' does not exist in folder 'c:\users\duh\documents\visual studio 2015\Projects\ConsoleApplication1\packages'
Install-Package : Could not install package 'KeystrokeAPI 1.0.6'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2', but the package does not contain any assembly 
references or content files that are compatible with that framework. For more information, contact the package author.
At line:1 char:1
+ Install-Package KeystrokeAPI
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId

**Comment by fabriciorissetto** [comment]
Yes @CarbonMan it is. Currently I'm deploying packages only to .NETFramework 4.6.

**Comment by CarbonMan** [comment]
Thanks, that's ok, I downloaded the package and rebuilt it.
