### ISSUE TITLE
System.AccessViolationException when "growing" in RAM by about 3MB

### ISSUE THREAD

**Issue by grimmbo93** [fabriciorissetto/KeystrokeAPI#2]
When running a program that uses your KeystrokeAPI but also when using the test app, at some point, mostly when the RAM consumption grew by approx. 3MB, the app throws a System.AccessViolationException. I can reproduce this Exception pretty easily by holding down backspace key on either machine i tried. Unfortunately there's no stack trace showing up. So can you figure out what might cause that Exception? Thanks!

Edit: To be more precise: It always happens after 720 pressed keys regardless of the exact key.

**Comment by fabriciorissetto** [comment]
Thank you @grimmbo93 for bringing this to me. The problem was related with the issue #4.
