### ISSUE TITLE
Random failure 

### ISSUE THREAD

**Issue by ukushu** [fabriciorissetto/KeystrokeAPI#4]
I geting random error
> Managed Debugging Assistant 'CallbackOnCollectedDelegate' has detected a problem in 'D:\Programming\KeyLogger\KL\KL\bin\Debug\KL.vshost.exe'.
> 
> Additional information: A callback was made on a garbage collected delegate of type 'KeystrokeAPI!Keystroke.API.User32+LowLevelHook::Invoke'. This may cause application crashes, corruption and data loss. When passing delegates to unmanaged code, they must be kept alive by the managed application until it is guaranteed that they will never be called.

To reproduce need to open any Windows Explorer window and try to press any keys few times.

**Comment by fabriciorissetto** [comment]
@grimmbo93 thanks for your feedback and by the steps details to reproduce the problem. 

The problem was that the GC was collecting the a delegate that it shouldn't. [This was exactly what was happening](http://stackoverflow.com/a/6145902/890890) :)

**Comment by fabriciorissetto** [comment]
https://www.nuget.org/packages/KeystrokeAPI/1.0.6.3
