### ISSUE TITLE
CallbackOnCollectedDelegate

### ISSUE THREAD

**Issue by IlTuoNome** [fabriciorissetto/KeystrokeAPI#9]
Error: "Additional information: A callback was made on a garbage collected delegate of type 'KeystrokeAPI!Keystroke.API.User32+LowLevelHook::Invoke'. This may cause application crashes, corruption and data loss. When passing delegates to unmanaged code, they must be kept alive by the managed application until it is guaranteed that they will never be called."

This error occurs to me if the program performs multiple operations

**Comment by hafizowais322** [comment]
I have same error but i am using win forms application and Application.Run(new Form1()) can not move. if i move from program.cs to form.cs application stops before started. plz resolve this issue
thx
